server:
  port: 8080
  servlet:
    context-path: /devops
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devops?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    #\u7F13\u51B2\u7684\u914D\u7F6E
    cache: false
    check-template: true
    check-template-location: true
    #\u5F00\u542FMVC thymeleaf \u89C6\u56FE\u89E3\u6790
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
#  profiles:
#    active: prd
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.trs.devopsdemo.domain.model

